version: "3.8"

services:
  core:
    container_name: tracker_core
    build:
      context: .
      dockerfile: docker/tracker_core/core.Dockerfile
    networks:
      - core_db_network
    ports:
      - "8000:8000"
    depends_on:
      - db_core
    env_file:
      - .core.env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8000/admin/login/"]
      interval: 1m
      timeout: 5s
      retries: 2

  db_core:
    container_name: db_core
    image: postgres:14-alpine
    networks:
      - core_db_network
    expose:
      - 5432
    env_file:
      - .core.env

networks:
  core_db_network: