# Generated by Django 4.1.4 on 2023-01-08 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('obj_type', models.CharField(choices=[('S', 'Supplies'), ('U', 'Utilities'), ('H', 'Home Routine'), ('O', 'Other')], default='O', max_length=255)),
                ('measure', models.IntegerField(default=0, max_length=255)),
                ('_measure_limit', models.IntegerField(max_length=255)),
                ('status', models.CharField(choices=[('G', 'Green'), ('O', 'Orange'), ('R', 'Red')], default='G', max_length=255)),
                ('lifelong_period', models.IntegerField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
            ],
        ),
    ]
