# Generated by Django 4.1.4 on 2023-01-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreobject',
            name='measure_unit',
            field=models.CharField(default='if not set, 1 is Green, 2 is Orange, 3 is Red', max_length=255),
        ),
    ]
