# Generated by Django 4.1.4 on 2023-01-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_coreobject_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreobject',
            name='_measure_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='lifelong_period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='measure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='obj_type',
            field=models.CharField(default='OTHER', help_text='You can use pre-defined dataset type (SUPPLIES, UTILITIES, HOME_ROUTINE, OTHER) or create your own', max_length=255),
        ),
    ]
