# Generated by Django 4.1.4 on 2023-01-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_coreobject__measure_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreobject',
            name='measure_unit',
            field=models.CharField(default='unit', max_length=255),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
