# Generated by Django 4.1.4 on 2023-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_coreobject_measure_unit_alter_coreobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreobject',
            name='measure',
            field=models.IntegerField(default=0, help_text='If not set, 1-Green, 2-Orange, 3-Red'),
        ),
    ]
