# Generated by Django 4.1.4 on 2023-02-07 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(default='OTHER', help_text='You can use pre-defined dataset type (SUPPLIES, UTILITIES, HOME_ROUTINE, OTHER) or create your own', max_length=255)),
                ('description', models.CharField(default='This is dataset description.', help_text='You can describe the dataset purpose or any other valuable details', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoreObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('measure', models.IntegerField(default=0, help_text='If not set, 1-Green, 2-Orange, 3-Red')),
                ('measure_limit', models.IntegerField(verbose_name='Measure limit')),
                ('measure_unit', models.CharField(default='unit', max_length=255)),
                ('status', models.CharField(choices=[('G', 'Green'), ('O', 'Orange'), ('R', 'Red')], default='G', max_length=255)),
                ('lifelong_period', models.IntegerField()),
                ('responsible', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(default='OTHER', on_delete=django.db.models.deletion.CASCADE, to='dashboard.dataset')),
            ],
            options={
                'ordering': ['status', 'dataset', 'responsible', 'name'],
            },
        ),
    ]
