# Generated by Django 4.1.4 on 2023-03-01 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(help_text='Give a name to your dataset', max_length=255)),
                ('description', models.CharField(help_text='Describe the dataset purpose or any other valuable details', max_length=70)),
                ('owner', models.ForeignKey(help_text='Current user name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoreObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Add the name of your task/goal/object', max_length=255)),
                ('description', models.CharField(help_text='Add short description of your task/goal/object', max_length=56)),
                ('current_value', models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], default='Green', help_text='Evaluate level of implementation according to measure description of your task/goal/object', max_length=6)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Orange', help_text='Choose priority of your task/goal/object status', max_length=8)),
                ('measure_description', models.CharField(default='Green-Orange-Red pattern (default)', help_text='Describe you 3-level pattern for evaluation of your task/goal/object.Based on these 3 levels the task/goal/object would have appropriateposition/color at the chart', max_length=63)),
                ('status', models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], default='Green', help_text='Status of implementation/performing/achieving of your task/goal/object.Status level is calculated comparing measure to measure limit.Based on status level the task/goal/object would have appropriateposition/color at the chart', max_length=6)),
                ('timeframe', models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Day', help_text='Choose a deadline/timeframe of your task/goal/object implementation.', max_length=5)),
                ('dataset', models.ForeignKey(help_text='Choose appropriate dataset for this task/goal/object', on_delete=django.db.models.deletion.CASCADE, to='dashboard.dataset')),
                ('responsible', models.ForeignKey(help_text='Current user name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'dataset', 'responsible', 'name'],
            },
        ),
    ]
