# Generated by Django 4.1.4 on 2023-02-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreobject',
            name='measure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='measure_unit',
            field=models.CharField(default='If not set, 1-Green, 2-Orange, 3-Red', max_length=255),
        ),
    ]
