# Generated by Django 4.1.4 on 2023-02-17 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_coreobject_measure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreobject',
            old_name='measure_unit',
            new_name='measure_description',
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='dataset',
            field=models.ForeignKey(default='OTHER', help_text='choose appropriate dataset for this task/goal/object', on_delete=django.db.models.deletion.CASCADE, to='dashboard.dataset'),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='description',
            field=models.CharField(help_text='short description of your task/goal/object', max_length=255),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='measure',
            field=models.IntegerField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], default='Green', help_text='evaluate level of implementation from 1 to 3 according to measure description of your task/goal/object'),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='measure_limit',
            field=models.IntegerField(choices=[('G', 'Green'), ('O', 'Orange'), ('R', 'Red')], default='O', help_text='choose appropriate dataset for this task/goal/object', verbose_name='Measure limit'),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='name',
            field=models.CharField(help_text='name of your task/goal/object', max_length=255),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='status',
            field=models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], default='Green', max_length=6),
        ),
    ]
