# Generated by Django 4.1.4 on 2023-02-17 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_alter_coreobject_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreobject',
            name='responsible',
            field=models.ForeignKey(help_text='current user name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='timeframe',
            field=models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Day', help_text='choose a deadline/timeframe of your task/goal/object implementation.', max_length=5),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset',
            field=models.CharField(help_text='give a name to your dataset', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.CharField(help_text='describe the dataset purpose or any other valuable details', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(help_text='current user name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
