# Generated by Django 4.1.4 on 2023-02-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_coreobject_responsible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreobject',
            name='description',
            field=models.CharField(help_text='add short description of your task/goal/object', max_length=255),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='measure',
            field=models.IntegerField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], default='Green', help_text='evaluate level of implementation by 3 levels according to measure description of your task/goal/object'),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='name',
            field=models.CharField(help_text='add the name of your task/goal/object', max_length=255),
        ),
    ]
