# Generated by Django 4.1.4 on 2023-02-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_coreobject_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreobject',
            name='measure',
            field=models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], default='Green', help_text='Evaluate level of implementation by 3 levels according to measure description of your task/goal/object', max_length=6),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='measure_limit',
            field=models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], default='Orange', help_text='Choose minimum satisfying level of your task/goal/object status', max_length=6),
        ),
    ]
