# Generated by Django 4.1.4 on 2023-02-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_coreobject_measure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreobject',
            old_name='measure_limit',
            new_name='priority',
        ),
    ]
