# Generated by Django 4.1.4 on 2023-02-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_measure_limit_coreobject_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreobject',
            name='priority',
            field=models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], default='Orange', help_text='Choose priority of your task/goal/object status', max_length=6),
        ),
    ]
