# Generated by Django 4.1.4 on 2023-02-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_coreobject_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreobject',
            name='measure',
        ),
        migrations.AddField(
            model_name='coreobject',
            name='current_value',
            field=models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], default='Green', help_text='Evaluate level of implementation according to measure description of your task/goal/object', max_length=6),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='description',
            field=models.CharField(help_text='Add short description of your task/goal/object', max_length=63),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='measure_description',
            field=models.CharField(default='Green-Orange-Red pattern (default)', help_text='Describe you 3-level pattern for evaluation of your task/goal/object.Based on these 3 levels the task/goal/object would have appropriateposition/color at the chart', max_length=63),
        ),
        migrations.AlterField(
            model_name='coreobject',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Orange', help_text='Choose priority of your task/goal/object status', max_length=8),
        ),
    ]
