# Generated by Django 4.1.4 on 2023-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_coreobject_measure_coreobject_current_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreobject',
            name='description',
            field=models.CharField(help_text='Add short description of your task/goal/object', max_length=56),
        ),
    ]
